Added submit button function
BayLadyCoder/spelling-practice pull request #9
Opened 2023-10-25 12:51 UTC by PentW0lf

As issue #1 , Submit button is created and it works fine.

2023-10-26 02:30 UTC, BayLadyCoder commented on index.html
> +      <button id="validateCurrentWord">Submit</button>
Can you make it snake-case like the other ids for consistency, pls?

2023-10-26 02:30 UTC, BayLadyCoder commented on index.js
> +const submitBtn = document.getElementById("validateCurrentWord");
Also, update id to snake-case here.

2023-10-26 02:31 UTC, BayLadyCoder commented on index.js
> +  const currentWord = wordsToPlay[currentWordIndex].toLowerCase();
Please remove `toLowerCase()` on both words because this practice is case sensitive.

2023-10-26 02:33 UTC, BayLadyCoder commented on index.js
> +    alert("That's wrong spelling,Please try again 💐");
Please correct this to "That's wrong spelling. Please try again 💐".

2023-10-26 02:35 UTC, BayLadyCoder requested changes
Thank you so much for your contribution. You did a good job, I just have some small change requests. I will try to add more details in the issues next time, so we have clearer requirements. 👍

2023-10-26 02:37 UTC, BayLadyCoder commented
I'd be really appreciate if you could attach some screenshots or screen recordings of the app that show how your changes work on the app.

2023-10-26 12:34 UTC, PentW0lf commented
Sure, I'll make the changes and attach a screenshot tomorrow as I'm away from my laptop for today.

2023-10-27 17:15 UTC, PentW0lf commented
Here is recording of working of app.

https://github.com/BayLadyCoder/spelling-practice/assets/31568025/8e77640d-0c22-460a-b57e-b2396d2082fd

2023-10-31 03:33 UTC, BayLadyCoder approved these changes

2023-10-31 03:33 UTC, merged